version: '3'
services:
  web:
    image: nginx:1.17.6-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx

  api:
    image: ruby:2.7.0
    ports:
      - "9292:9292"
    working_dir: /api
    volumes:
      - ./api:/api
      - ./api/vendor/bundle:/usr/local/bundle
    command: bundle exec rackup -o 0.0.0.0
